# Generated by Django 2.0 on 2018-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Picture', models.CharField(max_length=100)),
                ('Rating', models.IntegerField(max_length=10)),
                ('Notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
