# Generated by Django 2.0 on 2018-02-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180130_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song', models.CharField(max_length=200)),
                ('FileType', models.CharField(max_length=10)),
                ('Singer', models.CharField(max_length=200)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
        ),
    ]
